/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/basic': RouteRecordInfo<
      '/basic',
      '/basic',
      Record<never, never>,
      Record<never, never>,
      | '/basic/sandbox01'
      | '/basic/sandbox02'
      | '/basic/sandbox03'
    >,
    '/basic/sandbox01': RouteRecordInfo<
      '/basic/sandbox01',
      '/basic/sandbox01',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/basic/sandbox02': RouteRecordInfo<
      '/basic/sandbox02',
      '/basic/sandbox02',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/basic/sandbox03': RouteRecordInfo<
      '/basic/sandbox03',
      '/basic/sandbox03',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'src/pages/basic.vue': {
      routes:
        | '/basic'
        | '/basic/sandbox01'
        | '/basic/sandbox02'
        | '/basic/sandbox03'
      views:
        | 'default'
    }
    'src/pages/basic/sandbox01.vue': {
      routes:
        | '/basic/sandbox01'
      views:
        | never
    }
    'src/pages/basic/sandbox02.vue': {
      routes:
        | '/basic/sandbox02'
      views:
        | never
    }
    'src/pages/basic/sandbox03.vue': {
      routes:
        | '/basic/sandbox03'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
